version: '3'

services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 1s
      retries: 5
    environment:
      LANG: C.UTF-8
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docs_database
    volumes:
      - pgsql_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/postgres -user=postgres -password=postgres -locations=filesystem:/db/migration migrate
    volumes:
      - ./db/migration:/db/migration

volumes:
  pgsql_data:
    driver: local